# Generated by Django 2.2 on 2021-06-10 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0004_user_friended_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friended_users',
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(related_name='_user_friends_+', to='login_reg_app.User'),
        ),
    ]
