# Generated by Django 2.2 on 2021-06-10 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0005_auto_20210609_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(related_name='user_friends', to='login_reg_app.User'),
        ),
    ]
